version: '3.8'
services:
  ros2-humble:
    image: osrf/ros:humble-desktop-full
    container_name: ros2-humble
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ..:/workspace
      - ../ros2_ws:/root/ros2_ws
    working_dir: /root/ros2_ws
    command: tail -f /dev/null

  ros2-humble-cp:
    image: osrf/ros:humble-desktop-full
    container_name: ros2-humble-cp
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ..:/workspace
      - ../ros2_cp:/root/ros2_cp
    working_dir: /root/ros2_cp
    command: tail -f /dev/null
